### ISSUE TITLE
Hacer empanadas de pollo

### ISSUE THREAD

**Issue by estalvgs1999** [estalvgs1999/PROYECTO1.DotsGame#5]
Mi amor vea, necesitamos 50 empanadas de pollo, chicarrón y queso. Porfa que sea para el martes.
Además lleve cafecito y fresquito de papaya con melón.
=> BRETEE ESCLAVA

**Comment by Pablouc** [comment]
Bomboclat!

**Comment by tati2327** [comment]
Sí claro patroncito!! Quiere que barra también??

**Comment by Pablouc** [comment]
Al puro vuela
